# Introduction to numpy

In [7]:
import numpy as np


In [5]:
print(np.__version__)

2.1.3


In [ ]:
# to create a numpy array
myarr=np.array([12,14,15],np.int64)#np.int64 for memory management
print(myarr)

[12 14 15]


In [10]:
# to create a 2d numpy array
myarr2=np.array([[12,14,15],[1,2,3,]])
print(myarr2)
print(np.shape(myarr2))#tell numbers of rows and columns
print(myarr2[0,1])#to print a letter
myarr2[1,1]=50
print(myarr2)


[[12 14 15]
 [ 1  2  3]]
(2, 3)
14
[[12 14 15]
 [ 1 50  3]]


In [ ]:
zeross=np.zeros((2,5))
print(zeross)
rng=np.arange((15))
print(rng)
lspace=np.linspace(1,15,10)#equally space 10 element from 1 to 15 
print(lspace)
identity_array=np.identity(4)#make identity array
print(identity_array)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1.          2.55555556  4.11111111  5.66666667  7.22222222  8.77777778
 10.33333333 11.88888889 13.44444444 15.        ]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
arr3=np.arange(99)
print(arr3)
arr4=arr3.reshape(3,33)#//to split in 3 of 33
print(arr4)
arr5=arr3.ravel()
print(arr5)#to convert in 1d array



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [21]:
x=[[1,2,3],[4,5,6],[6,7,8]]
arr6=np.array(x)
print(arr6)
print(arr6.sum(axis=0))#sum all y axis element
print(arr6.sum(axis=1))#sum all x axis element

[[1 2 3]
 [4 5 6]
 [6 7 8]]
[11 14 17]
[ 6 15 21]


In [ ]:
#to generate random number
arr1=np.random.random(5)
print(arr1)
#for specific range
arr2=np.random.uniform(0.1,5.0,5)
print(arr2)




[0.23077407 0.7364242  0.60725524 0.86187318 0.49669923 0.82245181
 0.49610488 0.15795692 0.78704001 0.61635144 0.69936565 0.16152942
 0.44180849 0.95894681 0.39507247 0.65533739 0.52886418 0.75894166
 0.53335208 0.96392964]
[0.84645233 1.86427817 0.52999771 1.43598962 4.62303237 1.7579068
 2.17734261 4.80692102 1.44864286 1.86533048]
